# Generated by Django 2.1 on 2018-08-15 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deposito', '0003_auto_20180815_1025'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
