# Generated by Django 2.1 on 2018-08-08 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='fecha de pago')),
                ('estado', models.BooleanField(default=False)),
                ('usuario_asignado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarioAsignado', to='usuario.Usuario')),
                ('usuario_paga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarioPaga', to='usuario.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Requisitos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(verbose_name='fecha de creación')),
                ('fecha_ultima_modificacion', models.DateTimeField(verbose_name='última modificación')),
                ('estado', models.BooleanField(default=False)),
            ],
        ),
    ]
